name: Auto Commit

on:
  schedule:
    - cron: "*/1 * * * *"   # every 1 minute
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}

      - name: Make changes
        run: |
          echo "Auto commit at $(date)" >> log.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto commit at $(date)" || echo "No changes to commit"

      - name: Pull & Push changes
        run: |
          git pull --rebase --strategy-option=theirs origin ${{ github.ref_name }} || true
          git push origin HEAD:${{ github.ref_name }}
